### ISSUE TITLE
"Contact us" button should navigate to footer

### ISSUE THREAD

**Issue by manujuniris** [unbloxtech/3techiesbanter#7]
The contact us button should navigate to the footer of page instead of new page,

**Comment by manujuniris** [comment]
Hi @nilesh-uniris & @samiran-ghosh

The contact button now navigates to footer of page, please review https://unbloxtech.github.io/3tb-pre-production/index.html#footer

**Comment by nilesh-uniris** [comment]
The button navigates to the footer, but I have a few review observations:

- Whose number has been given under "Phone Details"?
- Who is monitoring the two email addresses under "Our Emails"?
- I sent a test message, where does the test message go? I could not complete the test since I don't have access to that mailbox.
- On submission by clicking "Send Message". The user is taken to Google Form. Can the user remain on the same page with the notification like "Thanks for contacting, we will revert soon."

**Comment by manujuniris** [comment]
Hi @nilesh-uniris 

- It's Vishnupriya mobile number.
- Also, Vishnupriya provided me the two emails.
- All reponses are recorded by google forms, 3techiesbanter@gmail.com (email) is used for the same.
- I can try to rework on alert message "Thanks for contacting, we will revert soon."

**Comment by manujuniris** [comment]
Hi @nilesh-uniris 

Changes are done ! Now the user remain on same page with a notification "Thanks for contacting, we will revert soon." 
Please review - https://unbloxtech.github.io/3tb-pre-production/#footer

**Comment by nilesh-uniris** [comment]
One small user experience issue remains. The message comes below the send message button so for me I thought nothing happened since nothing was visible. It felt like my form did not get submitted. The page does not move at all, and the message is not visible. If the message is shown above the form, below "Our Emails" and "Phone Details" then the experience would be better.

**Comment by manujuniris** [comment]
> One small user experience issue remains. The message comes below the send message button so for me I thought nothing happened since nothing was visible. It felt like my form did not get submitted. The page does not move at all, and the message is not visible. If the message is shown above the form, below "Our Emails" and "Phone Details" then the experience would be better.

Hi @nilesh-uniris 
Thanks for feedback, I have done the desired change, please review it via following link - 
https://unbloxtech.github.io/3tb-pre-production/#footer

**Comment by nilesh-uniris** [comment]
Looks fine now.
